RSpec.describe Translatomatic::ResourceFile::HTML do
  include_examples "a resource file", {
    # there are no keys in the html file, so they are just named 'key1', 'key2'
    autogenerated_keys: true
  }
end
