RSpec.describe Translatomatic::ResourceFile::HTML do
  include_examples "a resource file", {
    # there are no keys in the html file, so they are just named 'key1', 'key2'
    autogenerated_keys: true,
    locale_path_conversions: [
      #PathConversion.new("path/to/file.$EXT", "path/to/file.$EXT.$LOC"),
      PathConversion.new("path/to/file.$EXT", "path/to/file.$LOC.$EXT"),
      PathConversion.new("path/to/file.$EXT.$LOC", "path/to/file.$EXT.$LOC"),
      PathConversion.new("path/to/file.$LOC.$EXT", "path/to/file.$LOC.$EXT"),
    ]
  }
end
