RSpec.describe Translatomatic::ResourceFile::Plist do
  include_examples "a resource file", {
    # plist files have keys but they are not unique so we
    # are using autogenerated key names currently
    autogenerated_keys: true,
    locale_path_conversions: [
      PathConversion.new("$LOC.lproj/file.$EXT", "$LOC.lproj/file.$EXT"),
      PathConversion.new("path/to/file.$EXT", "path/to/file_$LOC.$EXT"),
      PathConversion.new("path/to/file_$LOC.$EXT", "path/to/file_$LOC.$EXT"),
    ]
  }
end
