RSpec.describe Translatomatic::ResourceFile::Subtitle do
  include_examples "a resource file", {
    autogenerated_keys: true,
    locale_path_conversions: [
      PathConversion.new("path/to/file.$EXT", "path/to/file_$LOC.$EXT"),
      PathConversion.new("path/to/file_$LOC.$EXT", "path/to/file_$LOC.$EXT"),
    ]
  }
end
