RSpec.describe Translatomatic::ResourceFile::XML do
  include_examples "a resource file", {
    # there are no keys in the xml file, so they are just named 'key1', 'key2'
    autogenerated_keys: true,
    test_files: %w{test.xml test2.xml},
    locale_path_conversions: [
      PathConversion.new("path/to/file.$EXT", "path/to/file_$LOC.$EXT"),
      PathConversion.new("path/to/file_$LOC.$EXT", "path/to/file_$LOC.$EXT"),
      PathConversion.new("res/values/file.$EXT", "res/values-$LOC/file.$EXT"),
      PathConversion.new("res/values-$LOC/file.$EXT", "res/values-$LOC/file.$EXT")
    ]
  }
end
