RSpec.describe Translatomatic::ResourceFile::XML do
  include_examples "a resource file", {
    # there are no keys in the xml file, so they are just named 'key1', 'key2'
    autogenerated_keys: true,
    test_files: %w{test.xml test2.xml}
  }
end
