RSpec.describe Translatomatic::ResourceFile::XML do
  include_examples "a resource file", {
    # there are no keys in the xml file, so they are just named 'key1', 'key2'
    autogenerated_keys: true,
    locale_path_conversions: [
      PathConversion.new("path/to/file.$EXT", "path/to/file_$LOC.$EXT"),
      PathConversion.new("path/to/file_$LOC.$EXT", "path/to/file_$LOC.$EXT"),
    ]
  }
end
